import './globals.css';

export const metadata = {
  title: 'NextJS13 Google Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
